apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: matheusjcn/intensive-microservices-catalog
        ports:
          - containerPort: 3334
        env:
          - name: PRODUCT_URL
            value: "http://product-service:3333"

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3334
  selector:
    app: catalog




