apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: matheusjcn/intensive-microservices-order
        # args: ["checkout_ex"]
        ports:
          # - containerPort: 3336
          - containerPort: 6572
        env:
          - name: PRODUCT_URL
            value: "http://product-service:3333"
          - name: RABBITMQ_ERLANG_COOKIE
            value: "SIRARTHURCONANDOYLE"
          - name: RABBITMQ_DEFAULT_USER
            value: "rabbitmq"
          - name: RABBITMQ_DEFAULT_PASS
            value: "rabbitmq"
          - name: RABBITMQ_DEFAULT_VHOST
            value: "/"
          - name: RABBITMQ_DEFAULT_HOST
            value: "rabbitmq-service"
          - name: REDIS_HOST
            value: "redis-service"
          - name: REDIS_PORT
            value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6572
  selector:
    app: order




